// Machine-generated by xckernel; do not edit.
// Reproduce with: python -m xckernel.emitters.gauxcwriter --emit <file>
// Copyright (c) 2026 Susi Lehtola.
#pragma once
#include <cmath>

namespace GauXC {
namespace xckernel {
/* machine-generated by xckernel; do not edit. */
// lda: per-function nuclear-displacement field rows.
// Sum over the basis functions of one atom to get the perturbed
// fields rho^(A,x), grad rho^(A,x) and tau^(A,x) at this point.
// dchi/ddchi carry the -d/dr sign and the atom mask.
static inline void xck_gauxc_hess_rows_lda(double U0_u, double U1_u, double U2_u, double U3_u, double dchi_gA_u, double ddchi_gA_u_x, double ddchi_gA_u_y, double ddchi_gA_u_z, double & F_rho, double & G_x, double & G_y, double & G_z) {
  F_rho = 2*U0_u*dchi_gA_u;
  G_x = 2*(U0_u*ddchi_gA_u_x + U1_u*dchi_gA_u);
  G_y = 2*(U0_u*ddchi_gA_u_y + U2_u*dchi_gA_u);
  G_z = 2*(U0_u*ddchi_gA_u_z + U3_u*dchi_gA_u);
}

/* machine-generated by xckernel; do not edit. */
// lda: non-Pulay pair term, per grid point.
// The fxc quadratic form on the two perturbed field sets, PLUS
// the sigma-curvature term 2 vsigma G^A . G^B -- sigma is
// quadratic in grad rho, so d2 sigma / dA dB survives for A /= B.
// Multiply by the quadrature weight at the call site.
static inline void xck_gauxc_hess_pair_lda(double F_rho_A, double F_rho_B, double v2rho2, double & h) {
  h = F_rho_A*F_rho_B*v2rho2;
}

/* machine-generated by xckernel; do not edit. */
// lda: Pulay term per basis-function PAIR, with the
// density-matrix factor D_uv DIVIDED OUT -- multiply by it,
// and by the quadrature weight, at the call site.
// Cannot factorise into an outer product; this is the only
// piece that needs the function pair.
static inline void xck_gauxc_hess_pulay_lda(double dchi_gA_u, double dchi_gB_v, double vrho, double w, double & s) {
  s = 2*dchi_gA_u*dchi_gB_v*vrho*w;
}

/* machine-generated by xckernel; do not edit. */
// lda: same-atom (delta_AB) term, per basis function.
// Complete over Cartesian components; multiply by the
// quadrature weight at the call site.
static inline void xck_gauxc_hess_same_lda(double U0_u, double d2chi_g2_u, double vrho, double w, double & s) {
  s = 2*U0_u*d2chi_g2_u*vrho*w;
}

/* machine-generated by xckernel; do not edit. */
// lda: Pulay point-weight matrix W_ab, weight included.
// Slots: 0 = displaced function, 1-3 = its displaced gradient.
// pulay_uv = sum_ab alpha_a(u) W_ab beta_b(v): contract the rows
// as matrix products rather than per function pair.
static inline void xck_gauxc_hess_pulayW_lda(double vrho, double w, double & W00) {
  W00 = 2*vrho*w;
}

/* machine-generated by xckernel; do not edit. */
// lda: d e(r_g) / d R_A, e = the unweighted energy density,
// basis class only (points fixed). No quadrature weight.
static inline void xck_gauxc_hess_egrad_lda(double F_rho_A, double vrho, double & de) {
  de = F_rho_A*vrho;
}

/* machine-generated by xckernel; do not edit. */
// gga: per-function nuclear-displacement field rows.
// Sum over the basis functions of one atom to get the perturbed
// fields rho^(A,x), grad rho^(A,x) and tau^(A,x) at this point.
// dchi/ddchi carry the -d/dr sign and the atom mask.
static inline void xck_gauxc_hess_rows_gga(double U0_u, double U1_u, double U2_u, double U3_u, double dchi_gA_u, double ddchi_gA_u_x, double ddchi_gA_u_y, double ddchi_gA_u_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double & F_rho, double & F_sigma, double & G_x, double & G_y, double & G_z) {
  const double t0 = U0_u*ddchi_gA_u_x + U1_u*dchi_gA_u;
  const double t1 = U0_u*ddchi_gA_u_y + U2_u*dchi_gA_u;
  const double t2 = U0_u*ddchi_gA_u_z + U3_u*dchi_gA_u;
  F_rho = 2*U0_u*dchi_gA_u;
  F_sigma = 4*grad_rho_x*t0 + 4*grad_rho_y*t1 + 4*grad_rho_z*t2;
  G_x = 2*t0;
  G_y = 2*t1;
  G_z = 2*t2;
}

/* machine-generated by xckernel; do not edit. */
// gga: non-Pulay pair term, per grid point.
// The fxc quadratic form on the two perturbed field sets, PLUS
// the sigma-curvature term 2 vsigma G^A . G^B -- sigma is
// quadratic in grad rho, so d2 sigma / dA dB survives for A /= B.
// Multiply by the quadrature weight at the call site.
static inline void xck_gauxc_hess_pair_gga(double F_rho_A, double F_rho_B, double F_sigma_A, double F_sigma_B, double G_A_x, double G_A_y, double G_A_z, double G_B_x, double G_B_y, double G_B_z, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & h) {
  h = F_rho_A*F_rho_B*v2rho2 + F_sigma_A*F_sigma_B*v2sigma2 + v2rhosigma*(F_rho_A*F_sigma_B + F_rho_B*F_sigma_A) + 2*vsigma*(G_A_x*G_B_x + G_A_y*G_B_y + G_A_z*G_B_z);
}

/* machine-generated by xckernel; do not edit. */
// gga: Pulay term per basis-function PAIR, with the
// density-matrix factor D_uv DIVIDED OUT -- multiply by it,
// and by the quadrature weight, at the call site.
// Cannot factorise into an outer product; this is the only
// piece that needs the function pair.
static inline void xck_gauxc_hess_pulay_gga(double dchi_gA_u, double dchi_gB_v, double ddchi_gA_u_x, double ddchi_gA_u_y, double ddchi_gA_u_z, double ddchi_gB_v_x, double ddchi_gB_v_y, double ddchi_gB_v_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double w, double & s) {
  const double t0 = 2*vsigma;
  const double t1 = dchi_gA_u*t0;
  const double t2 = dchi_gB_v*t0;
  s = 2*w*(dchi_gA_u*dchi_gB_v*vrho + ddchi_gA_u_x*grad_rho_x*t2 + ddchi_gA_u_y*grad_rho_y*t2 + ddchi_gA_u_z*grad_rho_z*t2 + ddchi_gB_v_x*grad_rho_x*t1 + ddchi_gB_v_y*grad_rho_y*t1 + ddchi_gB_v_z*grad_rho_z*t1);
}

/* machine-generated by xckernel; do not edit. */
// gga: same-atom (delta_AB) term, per basis function.
// Complete over Cartesian components; multiply by the
// quadrature weight at the call site.
static inline void xck_gauxc_hess_same_gga(double U0_u, double U1_u, double U2_u, double U3_u, double d2chi_g2_u, double d3chi_g2_u_x, double d3chi_g2_u_y, double d3chi_g2_u_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double w, double & s) {
  const double t0 = 2*vsigma;
  const double t1 = U0_u*t0;
  const double t2 = d2chi_g2_u*t0;
  s = 2*w*(U0_u*d2chi_g2_u*vrho + U1_u*grad_rho_x*t2 + U2_u*grad_rho_y*t2 + U3_u*grad_rho_z*t2 + d3chi_g2_u_x*grad_rho_x*t1 + d3chi_g2_u_y*grad_rho_y*t1 + d3chi_g2_u_z*grad_rho_z*t1);
}

/* machine-generated by xckernel; do not edit. */
// gga: Pulay point-weight matrix W_ab, weight included.
// Slots: 0 = displaced function, 1-3 = its displaced gradient.
// pulay_uv = sum_ab alpha_a(u) W_ab beta_b(v): contract the rows
// as matrix products rather than per function pair.
static inline void xck_gauxc_hess_pulayW_gga(double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double w, double & W00, double & W01, double & W02, double & W03, double & W10, double & W20, double & W30) {
  const double t0 = 4*vsigma*w;
  const double t1 = grad_rho_x*t0;
  const double t2 = grad_rho_y*t0;
  const double t3 = grad_rho_z*t0;
  W00 = 2*vrho*w;
  W01 = t1;
  W02 = t2;
  W03 = t3;
  W10 = t1;
  W20 = t2;
  W30 = t3;
}

/* machine-generated by xckernel; do not edit. */
// gga: d e(r_g) / d R_A, e = the unweighted energy density,
// basis class only (points fixed). No quadrature weight.
static inline void xck_gauxc_hess_egrad_gga(double F_rho_A, double F_sigma_A, double vrho, double vsigma, double & de) {
  de = F_rho_A*vrho + F_sigma_A*vsigma;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: per-function nuclear-displacement field rows.
// Sum over the basis functions of one atom to get the perturbed
// fields rho^(A,x), grad rho^(A,x) and tau^(A,x) at this point.
// dchi/ddchi carry the -d/dr sign and the atom mask.
static inline void xck_gauxc_hess_rows_mgga_tau(double U0_u, double U1_u, double U2_u, double U3_u, double dchi_gA_u, double ddchi_gA_u_x, double ddchi_gA_u_y, double ddchi_gA_u_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double & F_rho, double & F_sigma, double & F_tau, double & G_x, double & G_y, double & G_z) {
  const double t0 = U0_u*ddchi_gA_u_x + U1_u*dchi_gA_u;
  const double t1 = U0_u*ddchi_gA_u_y + U2_u*dchi_gA_u;
  const double t2 = U0_u*ddchi_gA_u_z + U3_u*dchi_gA_u;
  F_rho = 2*U0_u*dchi_gA_u;
  F_sigma = 4*grad_rho_x*t0 + 4*grad_rho_y*t1 + 4*grad_rho_z*t2;
  F_tau = U1_u*ddchi_gA_u_x + U2_u*ddchi_gA_u_y + U3_u*ddchi_gA_u_z;
  G_x = 2*t0;
  G_y = 2*t1;
  G_z = 2*t2;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: non-Pulay pair term, per grid point.
// The fxc quadratic form on the two perturbed field sets, PLUS
// the sigma-curvature term 2 vsigma G^A . G^B -- sigma is
// quadratic in grad rho, so d2 sigma / dA dB survives for A /= B.
// Multiply by the quadrature weight at the call site.
static inline void xck_gauxc_hess_pair_mgga_tau(double F_rho_A, double F_rho_B, double F_sigma_A, double F_sigma_B, double F_tau_A, double F_tau_B, double G_A_x, double G_A_y, double G_A_z, double G_B_x, double G_B_y, double G_B_z, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & h) {
  h = F_rho_A*F_rho_B*v2rho2 + F_sigma_A*F_sigma_B*v2sigma2 + F_tau_A*F_tau_B*v2tau2 + v2rhosigma*(F_rho_A*F_sigma_B + F_rho_B*F_sigma_A) + v2rhotau*(F_rho_A*F_tau_B + F_rho_B*F_tau_A) + v2sigmatau*(F_sigma_A*F_tau_B + F_sigma_B*F_tau_A) + 2*vsigma*(G_A_x*G_B_x + G_A_y*G_B_y + G_A_z*G_B_z);
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: Pulay term per basis-function PAIR, with the
// density-matrix factor D_uv DIVIDED OUT -- multiply by it,
// and by the quadrature weight, at the call site.
// Cannot factorise into an outer product; this is the only
// piece that needs the function pair.
static inline void xck_gauxc_hess_pulay_mgga_tau(double dchi_gA_u, double dchi_gB_v, double ddchi_gA_u_x, double ddchi_gA_u_y, double ddchi_gA_u_z, double ddchi_gB_v_x, double ddchi_gB_v_y, double ddchi_gB_v_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double vtau, double w, double & s) {
  const double t0 = 4*vsigma;
  const double t1 = dchi_gA_u*t0;
  const double t2 = dchi_gB_v*t0;
  s = w*(2*dchi_gA_u*dchi_gB_v*vrho + ddchi_gA_u_x*ddchi_gB_v_x*vtau + ddchi_gA_u_x*grad_rho_x*t2 + ddchi_gA_u_y*ddchi_gB_v_y*vtau + ddchi_gA_u_y*grad_rho_y*t2 + ddchi_gA_u_z*ddchi_gB_v_z*vtau + ddchi_gA_u_z*grad_rho_z*t2 + ddchi_gB_v_x*grad_rho_x*t1 + ddchi_gB_v_y*grad_rho_y*t1 + ddchi_gB_v_z*grad_rho_z*t1);
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: same-atom (delta_AB) term, per basis function.
// Complete over Cartesian components; multiply by the
// quadrature weight at the call site.
static inline void xck_gauxc_hess_same_mgga_tau(double U0_u, double U1_u, double U2_u, double U3_u, double d2chi_g2_u, double d3chi_g2_u_x, double d3chi_g2_u_y, double d3chi_g2_u_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double vtau, double w, double & s) {
  const double t0 = 4*vsigma;
  const double t1 = U0_u*t0;
  const double t2 = d2chi_g2_u*t0;
  s = w*(2*U0_u*d2chi_g2_u*vrho + U1_u*d3chi_g2_u_x*vtau + U1_u*grad_rho_x*t2 + U2_u*d3chi_g2_u_y*vtau + U2_u*grad_rho_y*t2 + U3_u*d3chi_g2_u_z*vtau + U3_u*grad_rho_z*t2 + d3chi_g2_u_x*grad_rho_x*t1 + d3chi_g2_u_y*grad_rho_y*t1 + d3chi_g2_u_z*grad_rho_z*t1);
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: Pulay point-weight matrix W_ab, weight included.
// Slots: 0 = displaced function, 1-3 = its displaced gradient.
// pulay_uv = sum_ab alpha_a(u) W_ab beta_b(v): contract the rows
// as matrix products rather than per function pair.
static inline void xck_gauxc_hess_pulayW_mgga_tau(double grad_rho_x, double grad_rho_y, double grad_rho_z, double vrho, double vsigma, double vtau, double w, double & W00, double & W01, double & W02, double & W03, double & W10, double & W11, double & W20, double & W22, double & W30, double & W33) {
  const double t0 = 4*vsigma*w;
  const double t1 = grad_rho_x*t0;
  const double t2 = grad_rho_y*t0;
  const double t3 = grad_rho_z*t0;
  const double t4 = vtau*w;
  W00 = 2*vrho*w;
  W01 = t1;
  W02 = t2;
  W03 = t3;
  W10 = t1;
  W11 = t4;
  W20 = t2;
  W22 = t4;
  W30 = t3;
  W33 = t4;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau: d e(r_g) / d R_A, e = the unweighted energy density,
// basis class only (points fixed). No quadrature weight.
static inline void xck_gauxc_hess_egrad_mgga_tau(double F_rho_A, double F_sigma_A, double F_tau_A, double vrho, double vsigma, double vtau, double & de) {
  de = F_rho_A*vrho + F_sigma_A*vsigma + F_tau_A*vtau;
}

/* machine-generated by xckernel; do not edit. */
// Becke/SSF confocal coordinate mu_DE = (|r-R_D| - |r-R_E|)/|R_D-R_E|,
// its gradient and full Hessian in (R_D, R_E) at fixed r.
static inline void xck_gauxc_weight_mu(double R_D_x, double R_D_y, double R_D_z, double R_E_x, double R_E_y, double R_E_z, double r_x, double r_y, double r_z, double & mu, double & dmu_0, double & dmu_1, double & dmu_2, double & dmu_3, double & dmu_4, double & dmu_5, double & d2mu_0_0, double & d2mu_0_1, double & d2mu_0_2, double & d2mu_0_3, double & d2mu_0_4, double & d2mu_0_5, double & d2mu_1_0, double & d2mu_1_1, double & d2mu_1_2, double & d2mu_1_3, double & d2mu_1_4, double & d2mu_1_5, double & d2mu_2_0, double & d2mu_2_1, double & d2mu_2_2, double & d2mu_2_3, double & d2mu_2_4, double & d2mu_2_5, double & d2mu_3_0, double & d2mu_3_1, double & d2mu_3_2, double & d2mu_3_3, double & d2mu_3_4, double & d2mu_3_5, double & d2mu_4_0, double & d2mu_4_1, double & d2mu_4_2, double & d2mu_4_3, double & d2mu_4_4, double & d2mu_4_5, double & d2mu_5_0, double & d2mu_5_1, double & d2mu_5_2, double & d2mu_5_3, double & d2mu_5_4, double & d2mu_5_5) {
  const double t0 = R_D_x - R_E_x;
  const double t1 = (t0*t0);
  const double t2 = R_D_y - R_E_y;
  const double t3 = (t2*t2);
  const double t4 = R_D_z - R_E_z;
  const double t5 = (t4*t4);
  const double t6 = t1 + t3 + t5;
  const double t7 = pow(t6, -1.0/2.0);
  const double t8 = -r_x;
  const double t9 = R_D_x + t8;
  const double t10 = (t9*t9);
  const double t11 = -r_y;
  const double t12 = R_D_y + t11;
  const double t13 = (t12*t12);
  const double t14 = -r_z;
  const double t15 = R_D_z + t14;
  const double t16 = (t15*t15);
  const double t17 = t10 + t13 + t16;
  const double t18 = sqrt(t17);
  const double t19 = R_E_x + t8;
  const double t20 = (t19*t19);
  const double t21 = R_E_y + t11;
  const double t22 = (t21*t21);
  const double t23 = R_E_z + t14;
  const double t24 = (t23*t23);
  const double t25 = t20 + t22 + t24;
  const double t26 = sqrt(t25);
  const double t27 = t18 - t26;
  const double t28 = 1.0/t18;
  const double t29 = 1.0/t6;
  const double t30 = t27*t29;
  const double t31 = t0*t30;
  const double t32 = t2*t30;
  const double t33 = t30*t4;
  const double t34 = 1.0/t26;
  const double t35 = t19*t34;
  const double t36 = t21*t34;
  const double t37 = t23*t34;
  const double t38 = 1.0/t17;
  const double t39 = t28*t9;
  const double t40 = t0*t39;
  const double t41 = 2*t29;
  const double t42 = 3*t29;
  const double t43 = t30*(t1*t42 - 1);
  const double t44 = pow(t17, -3.0/2.0);
  const double t45 = t44*t9;
  const double t46 = t12*t28;
  const double t47 = t0*t46;
  const double t48 = t2*t39;
  const double t49 = 3*t2;
  const double t50 = pow(t6, -2);
  const double t51 = t0*t27*t50;
  const double t52 = t49*t51;
  const double t53 = -t7*(t12*t45 + t29*t47 + t29*t48 - t52);
  const double t54 = t15*t28;
  const double t55 = t0*t54;
  const double t56 = t39*t4;
  const double t57 = 3*t4;
  const double t58 = t51*t57;
  const double t59 = -t7*(t15*t45 + t29*t55 + t29*t56 - t58);
  const double t60 = pow(t6, -3.0/2.0);
  const double t61 = t0*t35;
  const double t62 = 3*t30;
  const double t63 = t60*(-t1*t62 + t27 + t40 + t61);
  const double t64 = t0*t36;
  const double t65 = -t31*t49;
  const double t66 = t60*(t48 + t64 + t65);
  const double t67 = t0*t37;
  const double t68 = -t31*t57;
  const double t69 = t60*(t56 + t67 + t68);
  const double t70 = t2*t46;
  const double t71 = t30*(t3*t42 - 1);
  const double t72 = t2*t54;
  const double t73 = t4*t46;
  const double t74 = t27*t4*t49*t50;
  const double t75 = -t7*(t12*t15*t44 + t29*t72 + t29*t73 - t74);
  const double t76 = t2*t35;
  const double t77 = t60*(t47 + t65 + t76);
  const double t78 = t2*t36;
  const double t79 = t60*(t27 - t3*t62 + t70 + t78);
  const double t80 = t2*t37;
  const double t81 = -t32*t57;
  const double t82 = t60*(t73 + t80 + t81);
  const double t83 = t4*t54;
  const double t84 = t30*(t42*t5 - 1);
  const double t85 = t35*t4;
  const double t86 = t60*(t55 + t68 + t85);
  const double t87 = t36*t4;
  const double t88 = t60*(t72 + t81 + t87);
  const double t89 = t37*t4;
  const double t90 = t60*(t27 - t5*t62 + t83 + t89);
  const double t91 = 1.0/t25;
  const double t92 = pow(t25, -3.0/2.0);
  const double t93 = t19*t92;
  const double t94 = t7*(t21*t93 - t29*t64 - t29*t76 + t52);
  const double t95 = t7*(t23*t93 - t29*t67 - t29*t85 + t58);
  const double t96 = t7*(t21*t23*t92 - t29*t80 - t29*t87 + t74);
  mu = t27*t7;
  dmu_0 = t7*(t28*t9 - t31);
  dmu_1 = t7*(t12*t28 - t32);
  dmu_2 = t7*(t15*t28 - t33);
  dmu_3 = t7*(t31 - t35);
  dmu_4 = t7*(t32 - t36);
  dmu_5 = t7*(t33 - t37);
  d2mu_0_0 = -t7*(t28*(t10*t38 - 1) + t40*t41 - t43);
  d2mu_0_1 = t53;
  d2mu_0_2 = t59;
  d2mu_0_3 = t63;
  d2mu_0_4 = t66;
  d2mu_0_5 = t69;
  d2mu_1_0 = t53;
  d2mu_1_1 = -t7*(t28*(t13*t38 - 1) + t41*t70 - t71);
  d2mu_1_2 = t75;
  d2mu_1_3 = t77;
  d2mu_1_4 = t79;
  d2mu_1_5 = t82;
  d2mu_2_0 = t59;
  d2mu_2_1 = t75;
  d2mu_2_2 = -t7*(t28*(t16*t38 - 1) + t41*t83 - t84);
  d2mu_2_3 = t86;
  d2mu_2_4 = t88;
  d2mu_2_5 = t90;
  d2mu_3_0 = t63;
  d2mu_3_1 = t77;
  d2mu_3_2 = t86;
  d2mu_3_3 = t7*(t34*(t20*t91 - 1) - t41*t61 + t43);
  d2mu_3_4 = t94;
  d2mu_3_5 = t95;
  d2mu_4_0 = t66;
  d2mu_4_1 = t79;
  d2mu_4_2 = t88;
  d2mu_4_3 = t94;
  d2mu_4_4 = t7*(t34*(t22*t91 - 1) - t41*t78 + t71);
  d2mu_4_5 = t96;
  d2mu_5_0 = t69;
  d2mu_5_1 = t82;
  d2mu_5_2 = t90;
  d2mu_5_3 = t95;
  d2mu_5_4 = t96;
  d2mu_5_5 = t7*(t34*(t24*t91 - 1) - t41*t89 + t84);
}

/* machine-generated by xckernel; do not edit. */
// becke cell function s(mu) with t = s'/s and u = s''/s, from
// the factored ln s. Valid strictly inside the switching region
// (|mu| < 1 Becke, |mu| < a SSF); the host handles the outside.
static inline void xck_gauxc_weight_cell_becke(double mu, double & s, double & t, double & u) {
  const double t0 = mu - 1;
  const double t1 = mu + 2;
  const double t2 = (mu*mu*mu);
  const double t3 = (mu*mu);
  const double t4 = t3 - 3;
  const double t5 = t2*(t4*t4*t4);
  const double t6 = t3 - 1;
  const double t7 = t3*(t4*t4);
  const double t8 = -4*t3 + t6*t7 + 4;
  const double t9 = 36*mu;
  const double t10 = -12*t2 + t5 + t9 + 32;
  const double t11 = 3*mu - t2 + 4;
  const double t12 = 1.0/t11;
  const double t13 = -6*t12*t6 + 4/t1 + 8/t0;
  const double t14 = (t6*t6);
  const double t15 = -t4;
  s = -1.0/256.0*pow(t0, 8)*(t1*t1*t1*t1)*(((3.0/2.0)*mu - 1.0/2.0*t2 + 2)*((3.0/2.0)*mu - 1.0/2.0*t2 + 2))*(-9.0/4.0*mu + (3.0/4.0)*t2 - 1.0/16.0*t5 - 2);
  t = t13 + 9*t8/t10;
  u = -12*mu*t12 + 18*mu*(3*t14*t4 + t7 - 4)/t10 + ((t13 + 9*(-(t15*t15)*t3*t6 + 4*t3 - 4)/((t15*t15*t15)*t2 + 12*t2 - t9 - 32))*(t13 + 9*(-(t15*t15)*t3*t6 + 4*t3 - 4)/((t15*t15*t15)*t2 + 12*t2 - t9 - 32))) - 18*t14/(t11*t11) - 81*(t8*t8)/(t10*t10) - 4/(t1*t1) - 8/(t0*t0);
}

/* machine-generated by xckernel; do not edit. */
// ssf cell function s(mu) with t = s'/s and u = s''/s, from
// the factored ln s. Valid strictly inside the switching region
// (|mu| < 1 Becke, |mu| < a SSF); the host handles the outside.
static inline void xck_gauxc_weight_cell_ssf(double mu, double & s, double & t, double & u) {
  const double t0 = (mu*mu);
  const double t1 = (mu*mu*mu);
  const double t2 = 25*mu - 16;
  const double t3 = 16000*mu + 9375*t0 + 7424;
  const double t4 = 185600*mu + 200000*t0 + 78125*t1 + 65536;
  const double t5 = 1.0/t4;
  const double t6 = t3*t5 + 4/t2;
  s = (1.0/32.0)*(((25.0/16.0)*mu - 1)*((25.0/16.0)*mu - 1)*((25.0/16.0)*mu - 1)*((25.0/16.0)*mu - 1))*((725.0/16.0)*mu + (3125.0/64.0)*t0 + (78125.0/4096.0)*t1 + 16);
  t = 25*t6;
  u = -625*(t3*t3)/(t4*t4) + 6250*t5*(75*mu + 64) + 625*(t6*t6) - 2500/(t2*t2);
}
} // namespace xckernel
} // namespace GauXC
