compile:
	g++ test.cxx ../obara_saika.a /home/dtpopovici/Executables/libint/lib/libint2.a -o test.x -I/home/dtpopovici/Executables/libint/include -I/usr/local/include/eigen3 -I../include/ -std=c++1z
	g++ test1.cxx ../obara_saika.a /home/dtpopovici/Executables/libint/lib/libint2.a -o test1.x -I/home/dtpopovici/Executables/libint/include -I/usr/local/include/eigen3 -I../include/ -std=c++1z
	g++ test2.cxx ../obara_saika.a /home/dtpopovici/Executables/libint/lib/libint2.a -o test2.x -I/home/dtpopovici/Executables/libint/include -I/usr/local/include/eigen3 -I../include/ -std=c++1z
	g++ test3.cxx ../obara_saika.a /home/dtpopovici/Executables/libint/lib/libint2.a -o test3.x -I/home/dtpopovici/Executables/libint/include -I/usr/local/include/eigen3 -I../include/ -std=c++1z
